<?php

/**
 * Standard employment-standards overtime rules for provincially regulated employees.
 *
 * This is the default / most-common rule, not every exemption, averaging agreement,
 * or federally regulated workplace (Canada Labour Code).
 *
 * Amounts that depend on minimum wage are stored as dollar strings and dated.
 */
return [
    'retrieved_date' => '2026-09-06',
    'disclaimer' => 'These are standard employment-standards rules for most employees. Managers, some professions, averaging agreements, collective agreements, and federally regulated workplaces can differ. This is not legal advice.',
    'jurisdictions' => [
        'ON' => [
            'weekly_threshold' => 44,
            'daily_threshold' => null,
            'daily_double_threshold' => null,
            'multiplier' => '1.5',
            'double_multiplier' => null,
            'rate_basis' => 'regular',
            'minimum_wage' => null,
            'summary' => 'Most Ontario employees earn time-and-a-half after 44 hours in a work week. There is no general daily overtime threshold.',
            'exceptions' => 'Many jobs are exempt or have a higher threshold under ESA Regulation 285/01. Hours can be averaged over up to four weeks if there is a written agreement.',
            'source' => [
                'title' => 'Overtime pay — Your guide to the Employment Standards Act',
                'url' => 'https://www.ontario.ca/document/your-guide-employment-standards-act-0/overtime-pay',
                'publisher' => 'Government of Ontario',
            ],
        ],
        'QC' => [
            'weekly_threshold' => 40,
            'daily_threshold' => null,
            'daily_double_threshold' => null,
            'multiplier' => '1.5',
            'double_multiplier' => null,
            'rate_basis' => 'regular',
            'minimum_wage' => null,
            'summary' => 'Most Quebec employees earn time-and-a-half after 40 hours in a week under the Act respecting labour standards.',
            'exceptions' => 'Some sectors have a different standard workweek. Employees may request time off in lieu at the overtime rate. This calculator does not apply federal CLC rules.',
            'source' => [
                'title' => 'Hours of work and overtime',
                'url' => 'https://www.cnesst.gouv.qc.ca/en/working-conditions/hours-work-and-overtime',
                'publisher' => 'CNESST',
            ],
        ],
        'BC' => [
            'weekly_threshold' => 40,
            'daily_threshold' => 8,
            'daily_double_threshold' => 12,
            'multiplier' => '1.5',
            'double_multiplier' => '2.0',
            'rate_basis' => 'regular',
            'minimum_wage' => null,
            'summary' => 'British Columbia pays 1.5× after 8 hours in a day or 40 hours in a week, and 2× after 12 hours in a day. Only the first 8 hours each day count toward weekly overtime.',
            'exceptions' => 'Averaging agreements change how daily overtime is calculated. Some occupations are excluded from Parts of the Employment Standards Act.',
            'source' => [
                'title' => 'Overtime pay — Province of British Columbia',
                'url' => 'https://www2.gov.bc.ca/gov/content/employment-business/employment-standards-advice/employment-standards/hours/overtime-pay',
                'publisher' => 'Government of British Columbia',
            ],
        ],
        'AB' => [
            'weekly_threshold' => 44,
            'daily_threshold' => 8,
            'daily_double_threshold' => null,
            'multiplier' => '1.5',
            'double_multiplier' => null,
            'rate_basis' => 'regular',
            'minimum_wage' => null,
            'summary' => 'Alberta uses an 8/44 rule: overtime is hours over 8 in a day or 44 in a week, whichever produces more overtime hours, paid at 1.5× the wage rate.',
            'exceptions' => 'Some occupations are excluded or have special overtime formulas. Banking overtime is allowed only with a written agreement.',
            'source' => [
                'title' => 'Overtime hours and overtime pay',
                'url' => 'https://www.alberta.ca/overtime-hours-overtime-pay',
                'publisher' => 'Government of Alberta',
            ],
        ],
        'MB' => [
            'weekly_threshold' => 40,
            'daily_threshold' => 8,
            'daily_double_threshold' => null,
            'multiplier' => '1.5',
            'double_multiplier' => null,
            'rate_basis' => 'regular',
            'minimum_wage' => null,
            'summary' => 'Most Manitoba employees earn 1.5× after 8 hours in a day or 40 hours in a week.',
            'exceptions' => 'Standard hours can differ by permit or industry. This calculator uses the general 8/40 standard.',
            'source' => [
                'title' => 'Hours of work — Employment Standards fact sheet',
                'url' => 'https://www.gov.mb.ca/labour/standards/doc,hours-of-work,factsheet.html',
                'publisher' => 'Government of Manitoba',
            ],
        ],
        'SK' => [
            'weekly_threshold' => 40,
            'daily_threshold' => 8,
            'daily_double_threshold' => null,
            'multiplier' => '1.5',
            'double_multiplier' => null,
            'rate_basis' => 'regular',
            'minimum_wage' => null,
            'summary' => 'Most Saskatchewan employees earn 1.5× after 8 hours in a day or 40 hours in a week.',
            'exceptions' => 'Permits and some industries change standard hours. Collective agreements can set a different (not lower) overtime rule.',
            'source' => [
                'title' => 'Hours of work and overtime',
                'url' => 'https://www.saskatchewan.ca/business/employment-standards/hours-of-work-and-overtime',
                'publisher' => 'Government of Saskatchewan',
            ],
        ],
        'NS' => [
            'weekly_threshold' => 48,
            'daily_threshold' => null,
            'daily_double_threshold' => null,
            'multiplier' => '1.5',
            'double_multiplier' => null,
            'rate_basis' => 'regular',
            'minimum_wage' => null,
            'summary' => 'The general Nova Scotia rule is 1.5× the regular wage after 48 hours in a week.',
            'exceptions' => 'Some groups (including certain managers and industries) receive overtime at 1.5× the minimum wage instead, or after 110 hours over two weeks in construction. Transport has a two-week rule.',
            'source' => [
                'title' => 'Overtime — Employment Rights',
                'url' => 'https://novascotia.ca/lwd/employmentrights/overtime.asp',
                'publisher' => 'Government of Nova Scotia',
            ],
        ],
        'NB' => [
            'weekly_threshold' => 44,
            'daily_threshold' => null,
            'daily_double_threshold' => null,
            'multiplier' => '1.5',
            'double_multiplier' => null,
            'rate_basis' => 'greater_of_regular_or_min_ot',
            'minimum_wage' => '15.90',
            'summary' => 'New Brunswick requires overtime after 44 hours in a week. The statutory overtime floor is 1.5× the minimum wage ($15.90 as of 1 April 2026, so $23.85/hour). If your regular wage is already higher, the employer must still pay at least that regular wage for overtime hours unless a contract is more generous.',
            'exceptions' => 'The Employment Standards Act sets a minimum overtime rate of 1.5× minimum wage, not automatically 1.5× your regular wage. Contracts or policies can pay more.',
            'source' => [
                'title' => 'Minimum wage, overtime and minimum pay for reporting for work',
                'url' => 'https://www.gnb.ca/en/topic/jobs-workplaces/labour-market-workforce/employment-standards/wage-pay.html',
                'publisher' => 'Government of New Brunswick',
            ],
        ],
        'NL' => [
            'weekly_threshold' => 40,
            'daily_threshold' => null,
            'daily_double_threshold' => null,
            'multiplier' => '1.5',
            'double_multiplier' => null,
            'rate_basis' => 'regular',
            'minimum_wage' => null,
            'summary' => 'Most Newfoundland and Labrador employees have a 40-hour standard week with overtime at time and a half.',
            'exceptions' => 'Some occupations are excluded. Confirm the current Labour Standards fact sheets for your job.',
            'source' => [
                'title' => 'Labour standards',
                'url' => 'https://www.gov.nl.ca/aesl/lra/labourstandards/',
                'publisher' => 'Government of Newfoundland and Labrador',
            ],
        ],
        'PE' => [
            'weekly_threshold' => 48,
            'daily_threshold' => null,
            'daily_double_threshold' => null,
            'multiplier' => '1.5',
            'double_multiplier' => null,
            'rate_basis' => 'regular',
            'minimum_wage' => null,
            'summary' => 'Most Prince Edward Island employees earn 1.5× the regular rate after 48 hours in a week.',
            'exceptions' => 'Some employees are excluded from hours-of-work rules. There is no general daily overtime threshold.',
            'source' => [
                'title' => 'Hours of work',
                'url' => 'https://www.princeedwardisland.ca/en/information/workforce-advanced-learning-and-population/hours-of-work',
                'publisher' => 'Government of Prince Edward Island',
            ],
        ],
        'YT' => [
            'weekly_threshold' => 40,
            'daily_threshold' => 8,
            'daily_double_threshold' => null,
            'multiplier' => '1.5',
            'double_multiplier' => null,
            'rate_basis' => 'regular',
            'minimum_wage' => null,
            'summary' => 'Yukon generally pays 1.5× after 8 hours in a day or 40 hours in a week.',
            'exceptions' => 'Some professions and averaging arrangements differ. Federally regulated jobs use the Canada Labour Code instead.',
            'source' => [
                'title' => 'Employment standards',
                'url' => 'https://yukon.ca/en/employment-standards',
                'publisher' => 'Government of Yukon',
            ],
        ],
        'NT' => [
            'weekly_threshold' => 40,
            'daily_threshold' => 8,
            'daily_double_threshold' => null,
            'multiplier' => '1.5',
            'double_multiplier' => null,
            'rate_basis' => 'regular',
            'minimum_wage' => null,
            'summary' => 'Northwest Territories generally pays 1.5× after 8 hours in a day or 40 hours in a week.',
            'exceptions' => 'Exemptions and special rules apply to some occupations. This is the general standard only.',
            'source' => [
                'title' => 'Employment standards',
                'url' => 'https://www.ece.gov.nt.ca/en/services/employment-standards',
                'publisher' => 'Government of the Northwest Territories',
            ],
        ],
        'NU' => [
            'weekly_threshold' => 40,
            'daily_threshold' => 8,
            'daily_double_threshold' => null,
            'multiplier' => '1.5',
            'double_multiplier' => null,
            'rate_basis' => 'regular',
            'minimum_wage' => null,
            'summary' => 'Nunavut generally pays 1.5× after 8 hours in a day or 40 hours in a week.',
            'exceptions' => 'Some occupations are excluded. Confirm the Labour Standards Act for your workplace.',
            'source' => [
                'title' => 'Labour standards',
                'url' => 'https://www.gov.nu.ca/family-services/information/labour-standards',
                'publisher' => 'Government of Nunavut',
            ],
        ],
    ],
];
